version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - server/.env  # create from .env.example
    ports:
      - "8000:8000"
    restart: unless-stopped
